### ISSUE TITLE
clustering part

### ISSUE THREAD

**Issue by xixia03** [oezyurty/KCQRL#2]
Could you please confirm if there is no code for the clustering part?

**Comment by oezyurty** [comment]
Hi, as we have already provided the output of clustering in our repository (and the clustering itself is just a few lines of extra code), we didn't provide the script for clustering in the first place. 

However, for convenience, now you can find a script for the clustering [here](https://github.com/oezyurty/KCQRL/blob/main/kc_annotation/cluster_kcs.py). 

Hope this helps.
