### ISSUE TITLE
About model evaluation

### ISSUE THREAD

**Issue by NousEU** [oezyurty/KCQRL#3]
Thank you for your outstanding work. I have a question regarding the Evaluation. I met the following error messages when I used wandb_predict.py according to the instructions in the readme.It seems that the file "/question level/test sequences quelevel.csv" is required,how can i get this file?
![error](https://github.com/user-attachments/assets/dd1b7c0e-7d5c-435e-9e54-3e6523927ab0)
 I sincerely hope for your answers. Thank you!

**Comment by oezyurty** [comment]
Hi, thank you for your interest in our work and for your good comments! Did you download all the files provided by the original XES3G5M dataset? You can follow the link in our readme file.

**Comment by NousEU** [comment]
Thanks for your responses!I do download all the files  provided by the original XES3G5M dataset  according to the instructions in the readme? But I only get these files.
![image](https://github.com/user-attachments/assets/11c00492-02e0-447b-b127-e198d0c5b2c2)
I can't find the "test_sequences_quelevel.csv",I sincerely hope for your answers!

**Comment by NousEU** [comment]
Thanks for your responses! I successfully obtained those two files, but I encountered a new problem about Solution step generation.
![image](https://github.com/user-attachments/assets/78bc0434-1fff-43a9-a849-5b992845538d)
Is there any error in the running command provided on readme? Should we run the get_step_by_step_solutions.py at the first step?

**Comment by oezyurty** [comment]
Yes, you're definitely right! Thank you very much for spotting my typo in the README. I just fixed it now ;)

**Comment by NousEU** [comment]
I sincerely appreciate your response. I encountered the following issue during Step 3 - Solution Step - KC mapping. The error is caused by some entries missing the step_by_step_solution_list key, but when I checked the questions_translated_kc_sol_annotated.json file, I couldn't find the step_by_step_solution_list field. 
![image](https://github.com/user-attachments/assets/20c53292-9671-4518-bd57-4c0fb44e8ce5)
![image](https://github.com/user-attachments/assets/9cd1d32e-154b-48ae-bff2-59425ef96984)
Instead, there is only the step_by_step_solution_text field. The knowledge_concepts_list field also seems to have the same issue. Could you please advise where the error might have occurred? I sincerely appreciate your help!

**Comment by oezyurty** [comment]
Are you sure? The file [here](https://github.com/oezyurty/KCQRL/blob/main/data/XES3G5M/metadata/questions_translated_kc_sol_annotated_mapped.json) surely contains those fields.

**Comment by NousEU** [comment]
The final file questions_translated_kc_sol_annotated_mapped.json you provided surely contains those fields.But I encountered the the issue during Step 3 - Solution Step - KC mapping according to the readme.The file I got at the Step 2(questions_translated_kc_sol_annotated.json)  dose not contains those fields.
![image](https://github.com/user-attachments/assets/d633ef72-c79d-4bac-aaa5-90eea240f823)
I can not see the description about the step_by_step_solution_list field  and  knowledge_concepts_list field according to the file get_kc_annotations.py .
![image](https://github.com/user-attachments/assets/1a85a84c-7999-4aff-b644-67b1eda8b0bb)
